const jobProfileList = [
    {label: 'Frontend Developer', value: 0},
    {label: 'Backend Developer', value: 1},
    {label: 'Fullstack Developer', value: 2},
    {label: 'Data Science Engineer', value: 3},
    {label: 'Senior Data Analyst', value: 4},
    {label: 'Angular and Node Software Developer', value: 5},
    {label: 'Catalog Executive', value: 7},
    {label: 'Content Writer', value: 8},
    {label: 'CSM', value: 9},
    {label: 'Customer Success Manager', value: 10},
    {label: 'Data Analyst', value: 11},
    {label: 'Data Scientist', value: 12},
    {label: 'Delivery Manager', value: 13},
    {label: 'Digital Marketing', value: 14},
    {label: 'E-Commerce Operation Manager', value: 15},
    {label: 'Field Sales Executive', value: 16},
    {label: 'Flutter Developer', value: 17},
    {label: 'Internal Auditor - Consultant', value: 18},
    {label: 'IOS Developer', value: 19},
    {label: 'Key Accounts Manager', value: 20},
    {label: 'Marketing Analyst Expert', value: 21},
    {label: 'Operation Executive', value: 22},
    {label: 'Pre Sales', value: 23},
    {label: 'Product Owner B4', value: 24},
    {label: 'Regional Sales Head', value: 25},
    {label: 'Senior Java Developer', value: 26},
    {label: 'Senior Technical Architect', value: 27},
    {label: 'Sr Manager Demand Ops', value: 28},
    {label: 'Tech Writer', value: 29},
    {label: 'UX Lead', value: 30}
]

export default jobProfileList